"""Dump every E5-grid cell's pooled confusion matrix + 95% CI to a committed
markdown file, so slide editing does not need the (gitignored) probe JSONs.

The raw per-subject probe JSONs live under runs/ (gitignored), so this script
only runs on a machine that has them. Its OUTPUT
(results/v2_n78/e5_confusion_matrices.md) IS committed -- that is the
laptop-portable source of truth for the confusion matrices and CIs.

Run: .venv/Scripts/python.exe scripts/v2_e5_confusion.py
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from scipy import stats

ROOT = Path(__file__).resolve().parent.parent

CELLS = {
    "chind":        "v2_chind_no_bcic_n78",
    "G1 + full":    "v2_g1full_no_bcic_n78",
    "G1 + pos_only":"v2_g1posonly_no_bcic_n78",
    "G2 + full":    "v2_g2full_no_bcic_n78",
    "G2 + pos_only":"v2_g2posonly_no_bcic_n78",
    "G3 + full":    "v2_geometric_no_bcic_n78",
    "G3 + pos_only":"v2_geomposonly_no_bcic_n78",
}


def load(run: str) -> dict:
    p = ROOT / "runs" / "pretrain" / run / "probe_bcic_2b_loso.json"
    return json.loads(p.read_text())


def main():
    chind = load(CELLS["chind"])
    chps = {k: v["balanced_accuracy"] for k, v in chind["per_subject"].items()}

    out = ["# E5 ablation — pooled confusion matrices + 95% CI (zero-shot BCIC-2B, n=156)",
           "",
           "Pooled over the 9 BCIC-2B LOSO folds. Rows = true, cols = predicted; "
           "class 0 = Left MI, 1 = Right MI. CI = 95% paired CI of (cell − chind) "
           "per-subject BAC differences. Generated by `scripts/v2_e5_confusion.py` "
           "(reads gitignored probe JSONs; this file is the committed, laptop-portable copy).",
           ""]

    for name, run in CELLS.items():
        j = load(run)
        cm = j["aggregate"]["confusion_matrix"]
        tl, tr = cm[0], cm[1]
        rL = tl[0] / (tl[0] + tl[1]); rR = tr[1] / (tr[0] + tr[1])
        bac = (rL + rR) / 2
        if name == "chind":
            ci = "—"
        else:
            ps = {k: v["balanced_accuracy"] for k, v in j["per_subject"].items()}
            ks = sorted(set(ps) & set(chps))
            d = np.array([ps[k] for k in ks]) - np.array([chps[k] for k in ks])
            n = len(d); se = d.std(ddof=1) / np.sqrt(n); t = stats.t.ppf(0.975, n - 1)
            ci = f"[{d.mean() - t*se:+.3f}, {d.mean() + t*se:+.3f}]"
        out += [
            f"## {name} — BAC {bac:.3f}  (Δ vs chind CI {ci})",
            "",
            "|              | Pred Left | Pred Right | recall |",
            "|--------------|-----------|------------|--------|",
            f"| **True Left**  | {tl[0]} | {tl[1]} | {rL:.3f} |",
            f"| **True Right** | {tr[0]} | {tr[1]} | {rR:.3f} |",
            f"| row-norm %   | L→{rL*100:.1f}/{(1-rL)*100:.1f} | R→{(1-rR)*100:.1f}/{rR*100:.1f} | |",
            "",
        ]

    dest = ROOT / "results" / "v2_n78" / "e5_confusion_matrices.md"
    dest.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {dest}")


if __name__ == "__main__":
    main()
